stages:
    - test
    - build
    - deploy

image: alpine

test:
    stage: test
    script:
        - echo [STARTING TEST STAGE]
        - echo No tests yet...
        
build:
    stage: build
    
    tags:
        - docker-flask-app
    
    variables:
        REGION_NAME: "us-west-1"
        SERVICE_NAME: "simple-flask-app-service"
        CLUSTER_NAME: "flask-cluster"
    
    before_script: 
        - cd src

    script:
        - echo [STARTING BUILD STAGE]
        - docker build -t cturori/flask-app-demo:latest .
        - docker image push cturori/flask-app-demo:latest

deploy_prod:
    stage: deploy

    script:
        - echo [STARTING DEPLOY STAGE]
        - aws ecs update-service --deployment-configuration "maximumPercent=100,minimumHealthyPercent=0" --cluster $CLUSTER_NAME --service $SERVICE_NAME --region $REGION_NAME --force-new-deployment
        - echo "...AWS EC2 UPDATED"
    only:
        - master
