buildjob:
    stage: build
    
    tags:
        - docker-flask-app

    variables:
        REGION_NAME: "us-west-1"
        SERVICE_NAME: "simple-flask-app-service"
        CLUSTER_NAME: "flask-cluster"
    
    before_script: 
        - cd src

    script:
        - echo ...STARTING BUILD STAGE
        - echo $(pwd)
        - docker build -t cturori/flask-gitlabci-aws:latest .
        - echo ...LOCAL IMAGE BUILT
        - docker image push cturori/flask-app-demo:latest
        - echo ...IMAGE PUSHED TO DOCKER REGISTRY
        - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --region $REGION_NAME --force-new-deployment
        - echo "...AWS EC2 UPDATED"
