buildjob:
    stage: build
    tags:
        - docker-flask-app
    before_script: 
        - cd src
    script:
        - docker build -t cturori/flask-gitlabci-aws:latest .
        - echo "...local image built"
        - docker image push cturori/cturori/flask-app-demo:latest
        - echo "...image pushed to docker registry"
        - aws ecs update-service -cluster flask-cluster -service simple-flask-app-service --force-new-deployment
        - echo "...aws ec2 updated"