buildjob:
    stage: build
    tags:
        - docker-flask-app
    before_script: 
        - cd src
    script:
        - echo ...STARTING BUILD STAGE
        - echo $(pwd)
        - docker build -t cturori/flask-gitlabci-aws:latest .
        - echo ...LOCAL IMAGE BUILT
        - docker image push cturori/flask-app-demo:latest
        - echo ...IMAGE PUSHED TO DOCKER REGISTRY
        - aws ecs update-service --cluster flask-cluster --service simple-flask-app-service --force-new-deployment
        - echo "...AWS EC2 UPDATED"