buildjob:
    stage: build
    tags:
        - docker-flask-app
    variables:
        REGION: "us-west-1"
        SERVICE: "simple-flask-app-service"
        CLUSTER: "flask-cluster"
    before_script: 
        - cd src
    script:
        - echo ...STARTING BUILD STAGE
        - echo $(pwd)
        - docker build -t cturori/flask-gitlabci-aws:latest .
        - echo ...LOCAL IMAGE BUILT
        - docker image push cturori/flask-app-demo:latest
        - echo ...IMAGE PUSHED TO DOCKER REGISTRY
        - aws ecs update-service --deployment-configuration='{"maximumPercent":100,"minimumHealthyPercent":50}' --cluster $CLUSTER --service $SERVICE --region $REGION --force-new-deployment
        - echo "...AWS EC2 UPDATED"
