buildjob:
    stage: build
    tags:
        - docker-flask-app
    script:
        - docker build -t cturori/flask-gitlabci-aws:latest
        - docker image push cturori/flask-gitlabci-aws:latest
        - aws ecs update-service -cluster flask-cluster -service simple-flask-app-service --force-new-deployment
