version: "3"
services:
    web: 
        build: ./src
        entrypoint: 
            - flask
            - run
            - --host=0.0.0.0
        environment: 
            FLASK_ENV: development
            FLASK_APP: ./app.py
        ports: [5000:5000]
        volumes: ['./src:/src/app']